In [115]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re

In [116]:
#download the page and parse in soup
page = requests.get("https://www.healthecareers.com/search-jobs/?catid=&ps=100")
link = "https://www.healthecareers.com/search-jobs/?catid=&ps=100"
#Get HTML Content related to Chequing Account Names
soup = BeautifulSoup(page.content, 'html.parser')

In [117]:
#Find array of all the job locations for the first page of jobs
ok = soup.find_all(class_="job-location")
stringo = str(ok)

#find location in HTML
pattern = "id=\"job-results-location\">(.*?)</span>"
substring = re.findall(pattern, stringo)

state = [None] * len(substring) #Store all the states
city = [None] * len(substring) #Store all the cities

j = 0

#split by comma, put into two separate arrays -> one containing City and the other containing State
for stringy in substring:
    temp_strings = stringy.split(", ")
    if len(temp_strings) == 2:
        #print(temp_strings[1])
        city[j]=temp_strings[0]
        state[j]=temp_strings[1]
        #print(temp_strings) 
    j=j+1

    
df_new_s = pd.DataFrame(city)
df_new = pd.DataFrame(state) 
df = pd.DataFrame(df_new_s, columns = ['Cityy'])
df.insert(1, "States", df_new, True) 
df.insert(0, "City", df_new_s, True)
del df['Cityy']
df.head()

             City          States
0          Yakima      Washington
1            None            None
2           Elgin        Illinois
3          Summit              WI
4  Roanoke Rapids  North Carolina

In [118]:
#Find job locations on page 2 
#https://www.healthecareers.com/search-jobs/?catid=&ps=100&pg=2

#for loop here
i = 2

#edit the string for the ending of the page
original_URL= "https://www.healthecareers.com/search-jobs/?catid=&ps=100&pg=2"
updated_URL= original_URL[:-1] + str(i)


page = requests.get(updated_URL)
link = updated_URL
soup = BeautifulSoup(page.content, 'html.parser')

#Find array of all the job locations for the first page of jobs
ok = soup.find_all(class_="job-location")
stringo = str(ok)

#Find the location data
pattern = "id=\"job-results-location\">(.*?)</span>"
substring = re.findall(pattern, stringo)

#make dataframe of the existing data
state = [None] * len(substring) #Store all the states
city = [None] * len(substring) #Store all the cities

j = 0

#split by comma, put into two separate arrays -> one containing City and the other containing State
for stringy in substring:
    temp_strings = stringy.split(", ")
    if len(temp_strings) == 2:
        #print(temp_strings[1])
        city[j]=temp_strings[0]
        state[j]=temp_strings[1]
        #print(temp_strings) 
    j=j+1

    
df_new_s = pd.DataFrame(city)
df_new = pd.DataFrame(state) 
df2 = pd.DataFrame(df_new_s, columns = ['Cityy'])
df2.insert(1, "States", df_new, True) 
df2.insert(0, "City", df_new_s, True)
del df2['Cityy']

#append the new data and ignore the index values, need to save to a new value to store all the appended values too
df = df.append(df2, ignore_index = True)

In [119]:
df.tail()

           City          States
195  Fort Bragg  North Carolina
196  Fort Bragg  North Carolina
197  Fort Bragg  North Carolina
198  Fort Bragg  North Carolina
199  Fort Bragg  North Carolina

In [ ]:
#Find job locations on page 3 and onwards
#https://www.healthecareers.com/search-jobs/?catid=&ps=100&pg=2

#iterate through all remaining pages on the website
for iterations in range (3,91):

    #edit the string for the ending of the page
    original_URL= "https://www.healthecareers.com/search-jobs/?catid=&ps=100&pg=2"
    updated_URL= original_URL[:-1] + str(iterations)

    #pull page HTML data
    page = requests.get(updated_URL)
    link = updated_URL
    soup = BeautifulSoup(page.content, 'html.parser')

    #Find array of all the job locations for the first page of jobs
    ok = soup.find_all(class_="job-location")
    stringo = str(ok)

    #Find the location data
    pattern = "id=\"job-results-location\">(.*?)</span>"
    substring = re.findall(pattern, stringo)

    #make arrays for extracted information
    state = [None] * len(substring) #Store all the states
    city = [None] * len(substring) #Store all the cities

    j = 0

    #split by comma, put into two separate arrays -> one containing City and the other containing State
    for stringy in substring:
        temp_strings = stringy.split(", ")
        if len(temp_strings) == 2:
            #print(temp_strings[1])
            city[j]=temp_strings[0]
            state[j]=temp_strings[1]
            #print(temp_strings) 
        j=j+1

    #create dataframe
    df_new_s = pd.DataFrame(city)
    df_new = pd.DataFrame(state) 
    df2 = pd.DataFrame(df_new_s, columns = ['Cityy'])
    df2.insert(1, "States", df_new, True) 
    df2.insert(0, "City", df_new_s, True)
    del df2['Cityy']
    
    #append the new data and ignore the index values
    df = df.append(df2, ignore_index = True)

          City          States
95  Fort Bragg  North Carolina
96  Fort Bragg  North Carolina
97  Fort Bragg  North Carolina
98  Fort Bragg  North Carolina
99  Fort Bragg  North Carolina